language: php

sudo: false

php:
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_PUBLIC_KEY}\",\"password\":\"${MAGENTO_PRIVATE_KEY}\"}}}" > auth.json
    - composer install --prefer-dist

script:
    - php vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Api/ Block/ Controller/ Cron/ Helper/ Model/ Observer/ Setup/ Ui/
    - php vendor/bin/phpmd Api/,Block/,Controller/,Cron/,Helper/,Model/,Observer/,Setup/,Ui/ text unusedcode
    - php vendor/bin/phpcpd Api/ Block/ Controller/ Cron/ Helper/ Model/ Observer/ Setup/ Ui/

before_deploy:
    - rm -rf .github
    - rm -rf auth.json
    - rm -rf .travis.yml
    - rm -rf vendor
    - rm -rf .git
    - rm -rf composer.lock
    - zip -r membership.zip .

deploy:
    provider: releases
    api_key: "$GITHUB_OAUTH"
    file: "membership.zip"
    skip_cleanup: true
    on:
        tags: true
